spring:
  application:
    name: gateway
server:
  port: 8082
register:
  discovery:
    server-addr: localhost:8082
    service-name: gateway
    register-addr: localhost:8080
gateway:
  routes:
    - id: user-service
      uri: lb://user-service
      predicates:
        - Path=/user/**